const UPDATED_SUCCESSFULLY = "UPDATED_SUCCESSFULLY";
const CREATED_SUCCESSFULLY = "CREATED_SUCCESSFULLY";
const DELETED_SUCCESSFULLY = "DELETED_SUCCESSFULLY";
const EMAIL_SENT = "EMAIL_SENT";
const MEETING_CREATED = "MEETING_CREATED";
const ATTACTMENT_DELETED_SUCCESSFULLY = "ATTACTMENT_DELETED_SUCCESSFULLY";
const UPLOADED_SUCCESSFULLY = "UPLOADED_SUCCESSFULLY";

export { UPDATED_SUCCESSFULLY, CREATED_SUCCESSFULLY, DELETED_SUCCESSFULLY, EMAIL_SENT, MEETING_CREATED, ATTACTMENT_DELETED_SUCCESSFULLY, UPLOADED_SUCCESSFULLY };
